FROM node:20-alpine AS base
RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/ws ./apps/ws

RUN npm install -g prisma@6.5.0

RUN pnpm install --frozen-lockfile

WORKDIR /usr/src/app/packages/db
RUN prisma generate

WORKDIR /usr/src/app

RUN pnpm run build

EXPOSE 8080

CMD ["pnpm", "run", "start:ws"]